### ISSUE TITLE
Criar modelo fisico

### ISSUE THREAD

**Issue by Katleenmm** [vitoriaamaral09/Banco-de-dados-2#1]

**Comment by vitoriaamaral09** [comment]
Iniciação do Diagrama Físico.

**Comment by mlaurajeronimo** [comment]
Continuação do diagrama de modelo físico

**Comment by vitoriaamaral09** [comment]
![Untitled](https://github.com/user-attachments/assets/9921c387-b86d-434e-954c-f1b7d7c6bab1)

**Comment by vitoriaamaral09** [comment]
Foi corrigido o diagrama físico com o código 5f62e002156f9640487c31181cb4a703c6a22457

**Comment by vitoriaamaral09** [comment]
Corrigido o nome da linha ano_entrada para data_entrada para inserir a data completa e não somente o ano. f358fd83247ca4d0dbeb72f339985e0966e8ff6c

**Comment by vitoriaamaral09** [comment]
Adicionada mais um coluna (total_parcelas) na tabela empréstimo [d736dcf](https://github.com/vitoriaamaral09/Banco-de-dados-2/commit/d736dcf582851a60876c37a2bfd86572b438db7e)

**Comment by vitoriaamaral09** [comment]
Finalizado a parte referente a criação do diagrama fisico pelo dbdiagram.io e o script derivado desse
