### ISSUE TITLE
Preencher o tamplate do Excel

### ISSUE THREAD

**Issue by Katleenmm** [vitoriaamaral09/Banco-de-dados-2#2]

**Comment by mlaurajeronimo** [comment]
Início do preenchimento das tabelas do excel.

**Comment by mlaurajeronimo** [comment]
Após reajustes no diagrama de modelo fisico, fiz a alteração na tabela Excel.

**Comment by mlaurajeronimo** [comment]
[FINANCIAMENTO ESTUDANTE EXCEL.xlsx](https://github.com/user-attachments/files/17949895/FINANCIAMENTO.ESTUDANTE.EXCEL.xlsx)

**Comment by mlaurajeronimo** [comment]
em fase de ajustes final na tabela excel e implementação das índices

**Comment by mlaurajeronimo** [comment]
Tamplate excel: 
[excel financiamento estudantil.xlsx](https://github.com/user-attachments/files/17985832/excel.financiamento.estudantil.xlsx)
