### ISSUE TITLE
(PROF. JORGE) VALIDAR as issues sem RESPONSÁVEL

### ISSUE THREAD

**Issue by jlsilva01** [vitoriaamaral09/Banco-de-dados-2#4]
Todas as issues precisarão ter um responsável por ela.

![lista_atividades_sem_responsavel](https://github.com/user-attachments/assets/d58578e5-8c9c-4e04-8dea-13448762a889)

Validem as issues e efetuem as devidas correções.

**Comment by Katleenmm** [comment]
feito
