### ISSUE TITLE
Gerar script de criação do banco de dados

### ISSUE THREAD

**Issue by EuniceCorreia** [vitoriaamaral09/Banco-de-dados-2#6]
Gerar script de criação do banco de dados (SGDB relacional à sua escolha) e criar o banco de
dados.

**Comment by EuniceCorreia** [comment]
O arquivo foi gerado a partir do  dbdiagram.io. Já está concluído e postado por Vitória.

**Comment by vitoriaamaral09** [comment]
Foi gerado o script de criação do banco de dados (SGDB relacional à sua escolha) e criar o banco de
dados.

**Comment by vitoriaamaral09** [comment]
Encerrado a geração do script de criação do banco.
