### ISSUE TITLE
Criação de Objetos como: trigger, stored procedure, funções e índices.

### ISSUE THREAD

**Issue by EuniceCorreia** [vitoriaamaral09/Banco-de-dados-2#8]
Utilizar os seguintes objetos em seu projeto (mandatório): 1 função, 1 trigger, 1 stored
procedure, índices. Justificar a escolha de cada tipo de objeto para o desenvolvimento dos
códigos em seu sistema

**Comment by EuniceCorreia** [comment]
Aguardando a primeira parte do trabalho ficar pronta pra iniciar a criação do objetos e índices.

**Comment by EuniceCorreia** [comment]
Em Sala de aula dia 26/11/2024 fizemos atualização do Banco e iniciamos o projeto da criação dos objetos.

**Comment by EuniceCorreia** [comment]
Hoje estamos criando os objetos.

**Comment by Katleenmm** [comment]
procedure para adicionar pagamento criada

**Comment by Katleenmm** [comment]
trigger para alterar status de parcela quando for adicionado um pagamento criada

**Comment by EuniceCorreia** [comment]
Criação de Trigger para não deixar deletar qualquer dado da tabela pagamento.

**Comment by EuniceCorreia** [comment]
Store Procedure para trazer o Ranking dos 5 mais inadimplentes.

**Comment by EuniceCorreia** [comment]
Criação de Índices.

**Comment by EuniceCorreia** [comment]
Criação de Função, alteração no codigo proc. e incluir alguns comentarios.
Justificativas no código e apresentação.
