### ISSUE TITLE
Criar e responder a 6 questões de Negócios.

### ISSUE THREAD

**Issue by EuniceCorreia** [vitoriaamaral09/Banco-de-dados-2#9]
• Utilizar os objetos citados acima para responder 6 perguntas de negócio.

**Comment by EuniceCorreia** [comment]
Aguardando a conclusão das primeiras partes, pra poder iniciar a criação das perguntas e respostas.

**Comment by EuniceCorreia** [comment]
CRIAÇÃO DA 1 PERGUNTA DE NEGÓCIO

**Comment by mlaurajeronimo** [comment]
Criação da terceira pergunta de negócio.

**Comment by Katleenmm** [comment]
Criada a 4 pergunta de negócio

**Comment by Katleenmm** [comment]
Patricia fez a quinta

**Comment by HianRick** [comment]
Pergunta de negócio 6 concluida

**Comment by EuniceCorreia** [comment]
Vitória fez a 2ª Pergunta.
